create or replace TABLE DB_BRONZE_COMPANY.SCH_COLLECTOR_SYSTEM.BASE_VTAS (
	CUSTOMER_ID VARCHAR(100),
	ZONA VARCHAR(100),
	COUNTRY_CODE VARCHAR(100),
	ITEM_ID VARCHAR(100),
	CANAL_DE_VENTA VARCHAR(100),
	PRIORITY_ID VARCHAR(100),
	FECHA_PEDIDO VARCHAR(100),
	ID_PEDIDO VARCHAR(100),
	FECHA_ENVIO VARCHAR(100),
	UNIDADES VARCHAR(100),
	PRECIO_UNITARIO VARCHAR(100),
	COSTE_UNITARIO VARCHAR(100),
	IMPORTE_VENTA_TOTAL VARCHAR(100),
	IMPORTE_COSTE_TOTAL VARCHAR(100)
);